const serviceCardData = [
	{
		id: 1,
		title: "Customer Service",
		imgSrc: "/assets/images/h1.jpg",
		checks: [
			"Personal Information",
			"Insurance Information",
			"Medical History",
			"Guarantor Information",
			"Verification of Insurance Coverage",
			"Payment Arrangements",
			"Emergency Contact",
			"Consent Forms",
		],
		buttonText: "Consult Now",
	},
	{
		id: 2,
		title: "Insurance Verification",
		imgSrc: "/assets/images/h2.jpg",
		checks: [
			" Patient Demographic Information",
			"Insurance Plan Details",
			"Coverage and Benefits",
			"Network Verification",
			"Patient Financial Responsibility",
			" Coordination of Benefits",
			"Prior History of Claims",
			"Limits and Exclusions",
		],
		buttonText: "Consult Now",
	},
	{
		id: 3,
		title: "Medical Coding",
		imgSrc: "/assets/images/h3.jpg",
		checks: [
			"Use of Coding Systems",
			" Standardization of Medical Information",
			" Accuracy and Compliance",
			"Facilitating Billing and Reimbursement",
			"Medical Necessity",
			" Clinical Documentation",
			"Data for Research and Public Health",
			"Auditing and Compliance",
		],
		buttonText: "Consult Now",
	},
	{
		id: 4,
		title: "Claim Submission",
		imgSrc: "/assets/images/h4.jpg",
		checks: [
			"Accurate Information Gathering",
			" Insurance Verification",
			" Correct Use of Medical Codes",
			"Claim Form Preparation",
			"Claim Scrubbing",
			"  Timely Submission",
			"Payer-Specific Guidelines",
			"Claim Acknowledgment",
		],
		buttonText: "Consult Now",
	},
	{
		id: 5,
		title: "Insurance Review",
		imgSrc: "/assets/images/h6.jpg",
		checks: [
			" Eligibility Verification",
			" Covered Services Check",
			" Policy Terms and Limits",
			"Medical Necessity Review",
			"Correctness of Medical Coding",
			"Coordination of Benefits (COB)",
			"Payment Calculation",
			"Denial or Approval Decision",
		],
		buttonText: "Consult Now",
	},
	{
		id: 6,
		title: "Payment Posting",
		imgSrc: "/assets/images/h5.jpg",
		checks: [
			"Recording Payments",
			"Reconciliation",
			"Addressing Discrepancies",
			"Adjustments",
			"Denial and Appeal Management",
			"Patient Billing",
			"Reporting and Analytics",
			"Timely Updates",
		],
		buttonText: "Consult Now",
	},
	{
		id: 7,
		title: "Denial Management",
		imgSrc: "/assets/images/h7.jpg",
		checks: [
			"Understanding Denials",
			"Denial Tracking and Analysis",
			"Timely Follow-up",
			"Root Cause Identification",
			"Appeals Process",
			"Training and Education",
			"Prevention Strategies",
			"Metrics and Reporting",
		],
		buttonText: "Consult Now",
	},
	{
		id: 8,
		title: "Patient Billing",
		imgSrc: "/assets/images/h8.jpg",
		checks: [
			" Insurance Verification and Eligibility",
			"Medical Coding",
			"Claims Submission to Insurance",
			"Insurance Adjudication",
			"Patient Responsibility Determination",
			"Patient Billing Statement",
			"Payment Options and Plans",
			"Collections and Follow-Up",
		],
		buttonText: "Consult Now",
	},
];
export { serviceCardData };
